### ISSUE TITLE
Issue creating the conda environment

### ISSUE THREAD

**Issue by jackievaleri** [Bonidia/BioAutoML#1]
Hello! When I run the line "conda env create -f BioAutoML-env.yml -n bioautoml", I receive the below message. Up to this point, the git cloning of the repo and other installation steps worked fine. Should I be using different versions of these problematic packages? Thanks so much for your help!

```
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - cryptography==36.0.0=py37h9ce1e76_0
  - scipy==1.6.1=py37hf56f3a7_0
  - xorg-renderproto==0.11.1=h14c3975_1002
  - libxcb==1.13=h14c3975_1002
  - setuptools==52.0.0=py37h06a4308_1
  - pcre==8.44=he1b5a44_0
  - xorg-xproto==7.0.31=h14c3975_1007
  - xorg-libice==1.0.10=h516909a_0
  - libopenblas==0.3.7=h5ec1e0e_6
  - pysocks==1.7.1=py37h89c1867_4
  - zlib==1.2.11=h36c2ea0_1013
  - xorg-libxau==1.0.9=h14c3975_0
  - libgcc-ng==9.1.0=hdf63c60_0
  - bzip2==1.0.8=h516909a_3
  - libxgboost==1.5.0=h295c915_1
  - libuuid==2.32.1=h14c3975_1000
  - xorg-libx11==1.6.12=h36c2ea0_0
  - xorg-libxrender==0.9.10=h516909a_1002
  - py-xgboost==1.5.0=py37h06a4308_1
  - pixman==0.38.0=h516909a_1003
  - xz==5.2.5=h516909a_1
  - ncurses==6.2=h58526e2_4
  - lightgbm==3.2.1=py37h295c915_0
  - cairo==1.16.0=h3fc0475_1005
  - glib==2.58.3=py37he00f558_1004
  - icu==67.1=he1b5a44_0
  - scikit-learn==1.0.1=py37h51133e4_0
  - libgfortran4==7.5.0=h14aa051_19
  - libgomp==9.3.0=h5101ec6_17
  - xorg-libxdmcp==1.1.3=h516909a_0
  - libffi==3.2.1=he1b5a44_1007
  - pymongo==3.12.0=py37h295c915_0
  - python==3.7.3=h5b0a415_0
  - igraph==0.8.3=hef4adab_1
  - pycairo==1.20.0=py37h01af8b0_1
  - gmp==6.2.1=h58526e2_0
  - xorg-xextproto==7.3.0=h14c3975_1002
  - sqlite==3.33.0=h62c20be_0
  - openssl==1.1.1l=h7f8727e_0
  - pthread-stubs==0.4=h36c2ea0_1001
  - certifi==2021.10.8=py37h89c1867_1
  - cffi==1.15.0=py37h7f8727e_0
  - deap==1.3.1=py37h9fdb41a_2
  - fontconfig==2.13.1=h7e3eb15_1002
  - libstdcxx-ng==9.1.0=hdf63c60_0
  - libxml2==2.9.10=h68273f3_2
  - future==0.18.2=py37h89c1867_4
  - gettext==0.19.8.1=hf34092f_1004
  - numpy==1.19.2=py37h7008fea_1
  - python-igraph==0.8.3=py37h340e831_2
  - libiconv==1.16=h516909a_0
  - biopython==1.78=py37h4abf009_1
  - libgfortran-ng==7.5.0=h14aa051_19
  - xorg-kbproto==1.0.7=h14c3975_1002
  - brotlipy==0.7.0=py37hb5d75c8_1001
  - tk==8.6.10=h21135ba_1
  - pandas==0.25.3=py37hb3f55d8_0
  - libzlib==1.2.11=h36c2ea0_1013
  - xorg-libxext==1.3.4=h516909a_0
  - _openmp_mutex==4.5=1_gnu
  - catboost==1.0.3=py37h89c1867_1
  - readline==7.0=hf8c457e_1001
  - freetype==2.10.4=h7ca028e_0
  - ca-certificates==2021.10.26=h06a4308_2
  - xorg-libsm==1.2.3=h84519dc_1000
  - libedit==3.1.20191231=he28a2e2_2
  - libpng==1.6.37=h21135ba_2
```

**Comment by Bonidia** [comment]
Dear jackievaleri,

We hope this email finds you well!

First, apologies for the delay, I was away due to personal issues.

What is your operating system? I did some testing and it's working on debian and ubuntu!

Despite that, I uploaded some updates. Could you try again?

Please feel free to reach out if you need anything.

Best regards,

Robson P Bonidia.

**Comment by jackievaleri** [comment]
Hi Robson,

Thank you so much for your help. Unfortunately, when I tried again, I got very similar error messages. I am working on a M1 Mac running Monterey. My next step is trying this on an Ubuntu VM - thank you for the tip! I have included the errors below for your reference, but I will let you know my results in the Ubuntu test.

Thanks again!
-Jackie

`conda env create -f BioAutoML-env.yml -n bioautoml

Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - pysocks==1.7.1=py37h89c1867_4
  - libxml2==2.9.10=h68273f3_2
  - readline==7.0=hf8c457e_1001
  - xorg-xproto==7.0.31=h14c3975_1007
  - brotlipy==0.7.0=py37hb5d75c8_1001
  - future==0.18.2=py37h89c1867_4
  - libuuid==2.32.1=h14c3975_1000
  - xorg-libxau==1.0.9=h14c3975_0
  - cairo==1.16.0=h3fc0475_1005
  - python==3.7.3=h5b0a415_0
  - xorg-libx11==1.6.12=h36c2ea0_0
  - deap==1.3.1=py37h9fdb41a_2
  - libedit==3.1.20191231=he28a2e2_2
  - xorg-kbproto==1.0.7=h14c3975_1002
  - libopenblas==0.3.7=h5ec1e0e_6
  - libiconv==1.16=h516909a_0
  - libpng==1.6.37=h21135ba_2
  - certifi==2021.10.8=py37h89c1867_1
  - libgomp==9.3.0=h5101ec6_17
  - setuptools==52.0.0=py37h06a4308_1
  - libgfortran4==7.5.0=h14aa051_19
  - libxgboost==1.5.0=h295c915_1
  - zlib==1.2.11=h36c2ea0_1013
  - openssl==1.1.1o=h7f8727e_0
  - libgcc-ng==9.1.0=hdf63c60_0
  - scikit-learn==1.0.1=py37h51133e4_0
  - xorg-libice==1.0.10=h516909a_0
  - ca-certificates==2021.10.26=h06a4308_2
  - libzlib==1.2.11=h36c2ea0_1013
  - libgfortran-ng==7.5.0=h14aa051_19
  - pycairo==1.20.0=py37h01af8b0_1
  - py-xgboost==1.5.0=py37h06a4308_1
  - ncurses==6.2=h58526e2_4
  - xorg-libxext==1.3.4=h516909a_0
  - sqlite==3.33.0=h62c20be_0
  - _openmp_mutex==4.5=1_gnu
  - xz==5.2.5=h516909a_1
  - xorg-renderproto==0.11.1=h14c3975_1002
  - pthread-stubs==0.4=h36c2ea0_1001
  - pymongo==3.12.0=py37h295c915_0
  - gettext==0.19.8.1=hf34092f_1004
  - libxcb==1.13=h14c3975_1002
  - cryptography==36.0.0=py37h9ce1e76_0
  - xorg-libxrender==0.9.10=h516909a_1002
  - biopython==1.78=py37h4abf009_1
  - fontconfig==2.13.1=h7e3eb15_1002
  - cffi==1.15.0=py37h7f8727e_0
  - python-igraph==0.8.3=py37h340e831_2
  - bzip2==1.0.8=h516909a_3
  - freetype==2.10.4=h7ca028e_0
  - libffi==3.2.1=he1b5a44_1007
  - scipy==1.6.1=py37hf56f3a7_0
  - pandas==0.25.3=py37hb3f55d8_0
  - numpy==1.19.2=py37h7008fea_1
  - gmp==6.2.1=h58526e2_0
  - tk==8.6.10=h21135ba_1
  - xorg-libxdmcp==1.1.3=h516909a_0
  - pixman==0.38.0=h516909a_1003
  - catboost==1.0.3=py37h89c1867_1
  - igraph==0.8.3=hef4adab_1
  - icu==67.1=he1b5a44_0
  - libstdcxx-ng==9.1.0=hdf63c60_0
  - xorg-libsm==1.2.3=h84519dc_1000
  - xorg-xextproto==7.3.0=h14c3975_1002
  - lightgbm==3.2.1=py37h295c915_0
  - pcre==8.44=he1b5a44_0
  - glib==2.58.3=py37he00f558_1004`

**Comment by jackievaleri** [comment]
Creating the environment in Ubuntu 18.04 worked for me! Closing this issue - thank you for your help!
